name: environment
channels:
  - conda-forge
  - defaults
dependencies:
  
  - ipykernel=6.9.1
  - ipython=7.31.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jupyter_client=7.2.2
  - jupyter_core=4.11.1
  - jupyter_server=1.21.0
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.16.1
  - jupyterlab_widgets=1.0.0
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.2
  - notebook=6.4.11
  - numpy=1.21.6
  - pandas=1.2.5
  - pip=21.2.4
  - python=3.7.13
  - python-dateutil=2.8.2
  - tornado=6.1
  - voila=0.3.6
  - widgetsnbextension=3.5.2
  

